
const Map<String, String> labelDescriptions = {
  'Akhenaten':
      'Akhenaten was a pharaoh of ancient Egypt\'s 18th Dynasty, known for revolutionizing Egyptian religion by introducing the worship of a single god, Aten—the sun disk. He ruled from around 1353 to 1336 BCE and moved the capital to a new city called Akhenaten (modern-day Amarna). Akhenaten is also famous as the father of Tutankhamun and for his distinct artistic style that broke traditional conventions.',
  'Amenhotep III and Tiye':
      'Amenhotep III was a powerful pharaoh of Egypt\'s 18th Dynasty, who ruled during a time of great wealth, peace, and artistic achievement (c. 1391–1353 BCE). His wife, Queen Tiye, was one of the most influential queens in ancient Egyptian history. She was his trusted advisor and played a key role in diplomatic affairs. Statues and monuments often depict them together, highlighting their strong partnership and Tiye’s exceptional status.',
  'Bent Pyramid':
      'The Bent Pyramid, located in Dahshur, was built during the reign of Pharaoh Sneferu around 2600 BCE. It is unique for its distinctive shape—the lower part rises at a steep angle, which then shifts to a shallower angle near the top. This unusual design likely marks a transition in pyramid construction techniques. Sneferu, founder of Egypt’s 4th Dynasty, was a pioneer in building true pyramids, and the Bent Pyramid is a key step in the evolution toward the iconic Great Pyramid of Giza.',
  'Bust of Ramesses II':
      'The Bust of Ramesses II is a monumental statue fragment depicting one of ancient Egypt’s most powerful and celebrated pharaohs. Ramesses II, also known as Ramesses the Great, ruled for 66 years during the 19th Dynasty (c. 1279–1213 BCE). This granite bust showcases his regal features and is a symbol of his strength, legacy, and extensive building projects, including temples like Abu Simbel. Many such busts were created to honor his divine status and military achievements.',
  'Colossal Statue of Ramesses II':
      'This colossal statue represents Pharaoh Ramesses II, one of Egypt’s longest-reigning and most influential rulers. Carved from a single block of stone, the statue stands over 10 meters tall and showcases the pharaoh’s powerful, idealized form. It once adorned the temple complexes of ancient Egypt, symbolizing his divine authority and achievements. One of the most famous examples is the statue originally found in Memphis, now housed at the Grand Egyptian Museum.',
  'Colossi of Memnon':
      'The Colossi of Memnon are two massive stone statues of Pharaoh Amenhotep III, each standing about 18 meters tall. They once guarded the entrance to his mortuary temple in Thebes (modern-day Luxor). Built around 1350 BCE, these twin statues depict the pharaoh seated with his hands on his knees, gazing toward the Nile. In ancient times, one of the statues was said to "sing" at dawn—a phenomenon that made it a tourist attraction for the Greeks and Romans.',
  'Goddess Isis with her child':
      'This statue depicts the ancient Egyptian goddess Isis nursing her son, Horus. Isis was revered as a powerful mother, healer, and protector, while Horus would later become a major god associated with kingship and the sky. The image of Isis with the child Horus became a widespread symbol of motherhood and divine care, influencing artistic representations for centuries, even beyond Egypt. It reflects the deep spiritual and cultural values of ancient Egyptian society.',
  'Hatshepsut':
      'Hatshepsut was one of ancient Egypt’s most successful and powerful female pharaohs. She ruled during the 18th Dynasty (c. 1479–1458 BCE) and is known for her prosperous reign marked by peace, trade expansion, and monumental building projects—including her stunning mortuary temple at Deir el-Bahari. Hatshepsut often portrayed herself as a male king in statues and inscriptions to assert her authority. Her legacy highlights the capability and influence of women in ancient Egyptian leadership.',
  'Head Statue of Amenhotep III':
      'This statue fragment represents Pharaoh Amenhotep III, a ruler of Egypt’s 18th Dynasty known for his reign of peace, wealth, and grand architectural projects. The head is often carved from granite or quartzite and displays the pharaoh’s idealized facial features, symbolizing divine kingship and eternal youth. These statues were part of larger monumental works that honored his legacy and deified status during and after his reign (c. 1391–1353 BCE).',
  'Pyramid of Khafre':
      'The Pyramid of Khafre, located on the Giza Plateau, was built as the tomb of Pharaoh Khafre during Egypt’s 4th Dynasty (c. 2570 BCE). It is the second-largest pyramid at Giza and is distinctive for still having some of its original smooth casing stones near the top. The pyramid complex includes the Great Sphinx, believed to bear Khafre’s likeness, symbolizing royal power and protection.',
  'King Thutmose III':
      'Thutmose III was a powerful pharaoh of Egypt’s 18th Dynasty, often called the "Napoleon of Egypt" for his military genius. He reigned from around 1479 to 1425 BCE and expanded Egypt’s empire through numerous successful campaigns in the Near East and Nubia. Known for his ambitious building projects and extensive records, Thutmose III greatly strengthened Egypt’s power and influence.',
  'Mask of Tutankhamun':
      'The Mask of Tutankhamun is a stunning funerary artifact made of gold and precious stones, discovered in the young pharaoh’s tomb in the Valley of the Kings. Dating back to around 1323 BCE, it is one of the most famous symbols of ancient Egypt. The mask was designed to ensure the safe passage of Tutankhamun’s spirit to the afterlife, featuring intricate craftsmanship that highlights the pharaoh’s royal status and divine protection.',
  'Pyramid of Menkaure':
      'The Pyramid of Menkaure is the smallest of the three main pyramids on the Giza Plateau, built for Pharaoh Menkaure during Egypt’s 4th Dynasty around 2510 BCE. Despite its smaller size, it features a complex of temples and statues and is notable for its elegant proportions. Menkaure’s pyramid marks the final phase of the great pyramid-building era at Giza.',
  'Nefertiti':
      'Nefertiti was the Great Royal Wife of Pharaoh Akhenaten during Egypt’s 18th Dynasty. Renowned for her beauty and influence, she played a key role in the religious revolution that promoted the worship of the sun disk, Aten. The famous limestone bust of Nefertiti is celebrated worldwide as an icon of ancient Egyptian art and elegance.',
  'Pyramid of Djoser':
      'The Pyramid of Djoser, located in Saqqara, is the earliest colossal stone building in Egypt and the world’s first step pyramid. Built during the 27th century BCE for Pharaoh Djoser by his architect Imhotep, it marked a revolutionary shift in tomb construction. The stepped design served as a stairway for the pharaoh’s soul to ascend to the afterlife, setting the foundation for later pyramid architecture.',
  'Ramessum':
      'The Ramessum is the mortuary temple of Pharaoh Ramesses II, located on the west bank of the Nile near Luxor. Built to honor his legacy, it features massive statues, colossal gateways, and intricately carved reliefs depicting his military victories and divine status. The temple complex is a testament to Ramesses II’s power and architectural ambition during the 19th Dynasty.',
  'Sphinx':
      'The Great Sphinx of Giza is a massive limestone statue with the body of a lion and the head of a human, believed to represent Pharaoh Khafre. Carved around 2500 BCE, it stands as one of the most iconic symbols of ancient Egypt. The Sphinx symbolizes strength and wisdom and guards the Giza Plateau, overlooking the pyramids.',
  'King Zoser':
      'This statue represents Pharaoh Djoser, the ruler of Egypt’s 3rd Dynasty and the visionary behind the world’s first pyramid. The statue highlights his royal authority and divine status, reflecting the early artistic style of ancient Egypt. Djoser’s reign marked significant advances in architecture, most famously the Step Pyramid at Saqqara.',
  'Statue of Tutankhamun with Ankhesenamun':
      'This statue depicts the young Pharaoh Tutankhamun alongside his queen and half-sister, Ankhesenamun. It symbolizes their royal union and the restoration of traditional religious practices after the turbulent Amarna period. The statue reflects youthful elegance and the hope for Egypt’s future during Tutankhamun’s brief reign.',
  'Temple of Isis in Philae':
      'The Temple of Isis at Philae is one of the most famous ancient Egyptian temples dedicated to the goddess Isis, goddess of magic, motherhood, and fertility. Located on an island in the Nile near Aswan, the temple complex was a major religious center until the spread of Christianity. Built mainly during the Ptolemaic and Roman periods, it features beautiful reliefs and inscriptions celebrating Isis’s divine powers and her role in the myth of Osiris and Horus.',
  'Temple of Kom Ombo':
      'The Temple of Kom Ombo is a unique double temple located in Upper Egypt, dedicated to two gods: Sobek, the crocodile god of fertility and the Nile, and Horus the Elder, the falcon-headed god of the sky and war. Built during the Ptolemaic dynasty (around 180–47 BCE), the temple features symmetrical design, with duplicate courts, halls, and sanctuaries for each deity. Its walls are decorated with detailed reliefs depicting religious rituals, offerings, and medical instruments.',
  'The Great Temple of Ramesses II':
      'The Great Temple of Ramesses II at Abu Simbel is a monumental rock-cut temple complex built to honor Pharaoh Ramesses II and the gods. Constructed in the 13th century BCE, it features colossal statues of Ramesses II at the entrance and intricate interior reliefs depicting his military victories and divine status. The temple was famously relocated in the 1960s to avoid flooding from the Aswan High Dam, showcasing Egypt’s dedication to preserving its heritage.',
};
